### ISSUE TITLE
CommonInfo/CreatedInfo model improvements

### ISSUE THREAD

**Issue by jose-zitus** [math-a3k/django-ai#31]
### Update
This issue was posted in the wrong repo because of a confusión with names, it can be kindly ignored 

### Description

As of version 5.5.2 of django-ai-core, I believe there is a little room for improvement on this model:

- It uses default=now on created_at and lastmodified_at fields, instead of the good old auto_now=True and auto_now_add=True, which is cleaner and does not make these fields visible/editable on modelForms by default, which is ideal for audit purposes.
- The created_by and lastmodified_by fields should have the editable flag set to False so they are fully automatic and not visible on forms by default.

The current settings are not wrong, but I believe the ones I'm proposing suit more the typical use case for Django Models.

### How I believe the fields should look like

```
created_at = models.DateTimeField(_("Created at"), auto_now_add=True, db_index=True)
created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Created by"), blank=True, null=True,
                                   related_name="%(app_label)s_%(class)s_created", on_delete=models.SET_NULL, editable=False)
lastmodified_at = models.DateTimeField(_("Last modified at"), auto_now=True, db_index=True)
lastmodified_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Last modified by"), blank=True,
                                        null=True, related_name="%(app_label)s_%(class)s_lastmodified",
                                        on_delete=models.SET_NULL, editable=False)
```

**Comment by math-a3k** [comment]
[Wrong repository?](https://github.com/ambient-innovation/ai-django-core/issues/5) :)

If you would like to contribute, you are welcomed :) The current development is done in the [covid-ht](https://github.com/math-a3k/django-ai/tree/covid-ht) branch.

I don't see an exact fit it in the scope of django-ai, as the models provided are "internal" and intended to be minimalistic , it seems to me that if you want this functionality, you should include ai-django-core and subclass from CommonInfo.

But I'm open to discussion :)

**Comment by jose-zitus** [comment]
It was in fact the wrong repository! That's why i immediately closed the issue.

**Comment by math-a3k** [comment]
Nevermind then, it happens in all time, in the best families and it won't be my first time coding in the wrong window either :)

All the best!
